### ISSUE TITLE
Here's a list of issues I noticed which might help you out for future trainers.

### ISSUE THREAD

**Issue by iipythonix** [Glatrix/dddddd#1]
- I recommend watching this video so you can attach the window to the game window(not needed but might be something you wanted to go for):
https://youtu.be/t1ErGj0YnaM?list=PLBoJ8QcgGXk_Maz9z66V_wbfhbhQhluaR

- Level and Money both don't work (totally fine since this is still early development ofc)

- Change the check boxes for run speed and money to a type boxes rather than just button or checkbox and get what you get. (Just more flexibility for some who wish to change afterwards)

- Run speed only works if both boxes are checked

- For ESP (which I know you plan to add) have a check box that creates a transparent window and have it draw boxes on that window. Here's a somewhat good video explaining how to do that:
https://youtu.be/SPHARh6ukog

**The speed hack was tested as of the posted date**

~ None of these have to be changed accordingly just QOL for the people who are less knowledgeable for guis and tables. 
               ~ P.S. thanks for giving Gubna the tables early so he could let me test them lol, happy coding!

**Comment by Glatrix** [comment]
Actually, it does work. Its for the beta version of Phasmophobia. As of 3/3/2021, I'm still using it and updating it.
This version might be outdated though. go here for the latest https://www.unknowncheats.me/forum/phasmophobia/443271-simple-beta-speedhack.html#post3080450
